language: generic

sudo: required

# 2.
services:
  - docker

# 3.
before_install:
  - docker build -t chulhee23/react-test-app -f ./frontend/Dockerfile.dev ./frontend

# 4.
script:
  - docker run -e CI=true chulhee23/react-test-app npm run test

# 5 ~ 7
after_success:
  - docker build -t chulhee23/docker-frontend ./frontend
  - docker build -t chulhee23/docker-backend ./backend
  - docker build -t chulhee23/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push chulhee23/docker-frontend
  - docker push chulhee23/docker-backend
  - docker push chulhee23/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-fullstack-app"
  env: "DockerFullstackApp-env"
  bucket_name: elasticbeanstalk-ap-northeast-2-610947587757
  bucket_path: "docker-fullstack-app"
  
  on:
    branch: master
  
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY